[book]
authors = ["杜沛然"]
language = "en"
multilingual = false
src = "src"
title = "ray-tracing in one weekend"

[output.html]
git-repository-url = "https://github.com/dupeiran001/rust-ray-tracing-in-one-weekend"
mathjax-support = true
additional-css = ["./theme/style.css"]
additional-js = ["./theme/sidebar.js"]
